### ISSUE TITLE
  Credentials in profile "dbt_project", target "dev" invalid: Runtime Error

### ISSUE THREAD

**Issue by gkorland** [dagster-io/fake-star-detector#16]
```
2024-05-13 16:04:52 +0300 - dagster.builtin - ERROR - Encountered an error:
Runtime Error
  Credentials in profile "dbt_project", target "dev" invalid: Runtime Error
    Must specify schema
2024-05-13 16:04:53 +0300 - dagster.builtin - ERROR - Encountered an error:
Runtime Error
  Credentials in profile "dbt_project", target "dev" invalid: Runtime Error
    Must specify schema
2024-05-13 16:04:53 +0300 - dagster.code_server - ERROR - Error while importing code
Traceback (most recent call last):
  File "/home/guy/github/fake-star-detector/venv/lib/python3.12/site-packages/dagster/_core/errors.py", line 287, in user_code_error_boundary
    yield
  File "/home/guy/github/fake-star-detector/venv/lib/python3.12/site-packages/dagster/_grpc/server.py", line 242, in __init__
    loadable_targets = get_loadable_targets(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guy/github/fake-star-detector/venv/lib/python3.12/site-packages/dagster/_grpc/utils.py", line 50, in get_loadable_targets
    else loadable_targets_from_python_module(module_name, working_directory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guy/github/fake-star-detector/venv/lib/python3.12/site-packages/dagster/_core/workspace/autodiscovery.py", line 35, in loadable_targets_from_python_module
```

**Comment by aquinary** [comment]
Same issue. I'm using docker, and get this issue
